
Training step 0: loss = 0.0665336400270462
Training step 1: loss = 1787189.5
Training step 2: loss = 329792.75
Training step 3: loss = 330417.6875
Training step 4: loss = 11736.3056640625
Training step 5: loss = 319479.0
Training step 6: loss = 77659.6796875
Training step 7: loss = 928460.875
Training step 8: loss = 17436.998046875
Training step 9: loss = 1311064.5
roc_auc_score
0.9528409090909091
MCC
0.49910572351731713
Traceback (most recent call last):
  File "/Users/clementine/miniconda3/envs/NPG-env/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 4433, in _parse_scatter_color_args
    colors = mcolors.to_rgba_array(c)
  File "/Users/clementine/miniconda3/envs/NPG-env/lib/python3.10/site-packages/matplotlib/colors.py", line 487, in to_rgba_array
    rgba = np.array([to_rgba(cc) for cc in c])
  File "/Users/clementine/miniconda3/envs/NPG-env/lib/python3.10/site-packages/matplotlib/colors.py", line 487, in <listcomp>
    rgba = np.array([to_rgba(cc) for cc in c])
  File "/Users/clementine/miniconda3/envs/NPG-env/lib/python3.10/site-packages/matplotlib/colors.py", line 299, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/Users/clementine/miniconda3/envs/NPG-env/lib/python3.10/site-packages/matplotlib/colors.py", line 383, in _to_rgba_no_colorcycle
    raise ValueError("RGBA sequence should have length 3 or 4")
ValueError: RGBA sequence should have length 3 or 4
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/clementine/miniconda3/envs/NPG-env/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 4439, in _parse_scatter_color_args
    raise invalid_shape_exception(c.size, xsize) from err
ValueError: 'c' argument has 30 elements, which is inconsistent with 'x' and 'y' with size 20.
Backend MacOSX is interactive backend. Turning interactive mode on.